$wallDIR = $HOME/Pictures/wallpaper

# Startup
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Startup apps
exec-once = hyprpaper & 
exec-once = waybar & 
exec-once = hypridle & 
exec-once = nm-applet --indicator