# preload = ~/.config/hypr/wallpapers/Fantasy-Landscape3.png
# wallpaper = ,~/.config/hypr/wallpapers/Fantasy-Landscape3.png

wallpaper {
    monitor = DP-3
    path = ~/.config/hypr/wallpapers/Fantasy-Landscape3.png
}

splash = false