general {
    lock_cmd = pidof hyprlock || hyprlock       # Launch hyprlock if not running
    before_sleep_cmd = loginctl lock-session    # Lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on  # Turn on screen after sleep
}

listener {
    timeout = 150                                # 2.5min
    on-timeout = brightnessctl -s set 10         # Dim screen
    on-resume = brightnessctl -r                 # Restore screen brightness
}

listener {
    timeout = 300                                # 5min
    on-timeout = loginctl lock-session          # Lock screen
}

listener {
    timeout = 330                                # 5.5min
    on-timeout = hyprctl dispatch dpms off       # Screen off
    on-resume = hyprctl dispatch dpms on         # Screen on
}